[package]
name = "launchy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
egui = "0.33.3"
eframe = "0.33.3"
serde = "1.0.228"
serde_derive = "1.0.228"
toml = "0.9.11"
image = "0.24"
reqwest = { version = "0.11", features = ["blocking"] }
sha2 = "0.10.9"
